# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://gdgspain-open-source.github.io
title: Open GDG Spain
email: gdgspain@gmail.com
author: Oscar Caballero (Oscar Caballero)
description: > # "This is awesome description about web"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/gdgspain-open-source
