# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://gdgspain.github.io
title: Open GDG Spain
email: info@gdg.es
author: Oscar Caballero (@oscar_pozas)
description: > # "This is awesome description about web"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/GDGSpain
